apiVersion: apps/v1
kind: Deployment
metadata:
  name: base-web-single-host-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: base-web-single-host
  template:
    metadata:
      labels:
        app: base-web-single-host
    spec:
      containers:
        - name: app
          image: serverless-registry.cn-shanghai.cr.aliyuncs.com/opensource/test/base_mqtt:0.0.2
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: "200m"
              memory: "200Mi"